on:
  schedule:
    - cron:  '* * * * *'
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: volta-cli/action@v4
      - run: npm install
      - run: npm run cron